{
 "title": "Elasticsearch - History Stats",
 "description": "Grafana Dashboards for Elasticsearch using Prometheus Datasource. Dashboard for History Stats.",
 "tags": [
  "elasticsearch",
  "es-cluster-hist"
 ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(elasticsearch_indices_docs,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
    }
   },
   {
    "name": "name",
    "label": "Node name",
    "query": {
     "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(elasticsearch_index_stats_get_total{instance=\"$instance\",cluster=\"$cluster\"},index)"
    }
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "day",
    "label": "Day",
    "query": "1d,2d,3d,4d,5d,6d,7d,8d,9d,10d,11d,12d,13d,14d,15d,16d,17d,18d,19d,20d,21d,22d,23d,24d,25d,26d,27d,28d,29d,30d"
   },
   {
    "name": "day1",
    "label": "Day",
    "query": "1d,2d,3d,4d,5d,6d,7d,8d,9d,10d,11d,12d,13d,14d,15d,16d,17d,18d,19d,20d,21d,22d,23d,24d,25d,26d,27d,28d,29d,30d"
   },
   {
    "name": "day2",
    "label": "Day",
    "query": "1d,2d,3d,4d,5d,6d,7d,8d,9d,10d,11d,12d,13d,14d,15d,16d,17d,18d,19d,20d,21d,22d,23d,24d,25d,26d,27d,28d,29d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Level - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Indexing - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\nsum (rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval])) / \nsum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day)), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day1)), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day2)), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  },
  {
   "title": "Cluster Search Query - $cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\n(sum(rate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_scroll_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_suggest_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n) /\nsum(rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day)), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day1)), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval] offset $day2)), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  },
  {
   "title": "Node Level - $name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Indexing - $name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\nrate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) / rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day1), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day2), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  },
  {
   "title": "Node Search Query - $name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\n(rate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_scroll_time_seconds{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n+ rate(elasticsearch_indices_search_suggest_time_seconds{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n) /\nrate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day1), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval] offset $day2), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  },
  {
   "title": "Index Level - $index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Indexing - $index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\nrate(elasticsearch_index_stats_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval]) / rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day1), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day2), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  },
  {
   "title": "Search Query - $index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])",
     "legendFormat": "Today"
    },
    {
     "expr": "1 / (\n(rate(elasticsearch_index_stats_search_query_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_fetch_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_scroll_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n+ rate(elasticsearch_index_stats_search_suggest_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n) / rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval])\n)",
     "legendFormat": "ProcRate - Today"
    },
    {
     "expr": "label_replace(rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day), \"time\", \"$day\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_index_stats_search_query_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day1), \"time\", \"$day1\", \"\", \".*\") or\nlabel_replace(rate(elasticsearch_index_stats_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\",index=~\"$index\"}[$interval] offset $day2), \"time\", \"$day2\", \"\", \".*\")",
     "legendFormat": "Last {{ time }}"
    }
   ]
  }
 ]
}